# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ts_degree <- function(net, ego) {
    .Call('_RsienaTwoStep_ts_degree', PACKAGE = 'RsienaTwoStep', net, ego)
}

ts_recip <- function(net, ego) {
    .Call('_RsienaTwoStep_ts_recip', PACKAGE = 'RsienaTwoStep', net, ego)
}

ts_names <- function(x) {
    .Call('_RsienaTwoStep_ts_names', PACKAGE = 'RsienaTwoStep', x)
}

set_function_names <- function() {
    invisible(.Call('_RsienaTwoStep_set_function_names', PACKAGE = 'RsienaTwoStep'))
}

