---
title: "Retrieve parameters from ABM-twostep via RSiena"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{css, echo=FALSE}
.test {
  max-height: 300px;
  overflow-y: auto;
  overflow-x: auto;
  margin: 10px;
}

.test2 {
  max-height: 300px;
  overflow-y: auto;
  overflow-x: auto;
  margin: 10px;
  background-color: white;
  color: rgb(201, 76, 76);
}


h1, .h1, h2, .h2, h3, .h3 {
  margin-top: 24px;
}





.button1 {
  background-color: grey; /* Red */ 
  border: 2px solid black;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  /* border-radius: 12px; */
  width: 100%;
}

.button1:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
}

.button1:active {
  border: 2px solid red;
}

pre {
  max-height: 300px;
  overflow-y: auto;
  overflow-x: auto;
  margin: 0px;
}

.watch-out {
  background-color: lightpink;
  border: 3px solid red;
  font-weight: bold;
}

.large {
  max-height: 1100px;
  overflow-y: auto;
  overflow-x: auto;
  width: 1100px;
}


body{ /* Normal  */
    font-size: 14px;
}

h1 { /* Header 1 */
    font-size: 20px;
  font-weight: bold;
}

h2 { /* Header 2 */
    font-size: 18px;
  color: DarkBlue;
}

h3 { /* Header 3 */
    font-size: 16px;
  color: DarkBlue;
}

blockquote {
  padding: 10px 20px;
  margin: 0 0 20px;
  font-size: 14px;
  border-left: 6px solid #eee;
  background-color:lightcyan
}

caption {
  font-size: 14px;
  color: black;
  font-weight: bold
}

pre.numberSource a.sourceLine {
  left: -1em;
}

```

# 1. Getting started


```{r}
rm(list=ls())
```


## 1.1. Basic functions  


```{r}
fsave <- function(x, file, location = "./data/processed/", ...) {
    if (!dir.exists(location))
        dir.create(location)
    datename <- substr(gsub("[:-]", "", Sys.time()), 1, 8)
    totalname <- paste(location, datename, file, sep = "")
    print(paste("SAVED: ", totalname, sep = ""))
    save(x, file = totalname)
}

fpackage.check <- function(packages) {
    lapply(packages, FUN = function(x) {
        if (!require(x, character.only = TRUE)) {
            install.packages(x, dependencies = TRUE)
            library(x, character.only = TRUE)
        }
    })
}

colorize <- function(x, color) {
    sprintf("<span style='color: %s;'>%s</span>", color, x)
}

```

## 1.2. Packages

```{r}
packages = c("RsienaTwoStep", "doParallel", "ggplot2")

fpackage.check(packages)
```

---  

# 2. Setting up cluster

```{r}
#stopCluster(my.cluster) 
n.cores <- parallel::detectCores() - 1  #save one core for other work
# create the cluster
my.cluster <- parallel::makeCluster(n.cores, type = "PSOCK")
# register it to be used by %dopar%
doParallel::registerDoParallel(cl = my.cluster)
```

---  

# 3. Pick simulated network. 

We simulated the network via the following code: 

```{r, eval=FALSE}
sims3 <- ts_sims(nsims=nsims, parallel=TRUE, net=net1, rate=10, statistics=list(ts_degree, ts_recip, ts_transTrip, ts_transMedTrip), parameters=c(-2,1,2,2), p2step=1, dist1=2, dist2=2, chain=FALSE) #twostep: weak
```

```{r, eval=TRUE, echo=FALSE}
load(20221221.sims3.Rdata)
```

### 3.3.2. Counting dyads

```{r, eval=FALSE}
df <- ts_dyads(sims=sims3, simtype="twostep: weak coordination")  
```


### 3.3.3. Plot results of the dyadcensus 

```{r, fig.cap="Figure 3.3.3. Dyadcensus Model"}
p <- ggplot(df, aes(x=x, y=y, fill=factor(type, levels=c("twostep: simultaneity")))) + 
  geom_violin(position=position_dodge(.9)) + 
  stat_summary(fun = mean,
               geom = "errorbar",
               fun.max = function(x) mean(x) + sd(x),
               fun.min = function(x) mean(x) - sd(x),
               width=.1,
               color="red", position=position_dodge(.9)) + 
  stat_summary(fun = mean,
               geom = "point",
               color="red", position=position_dodge(.9)) +
  labs(x = "dyad type", y = "dyad count", fill="simulation type")
  
p


```


### 3.3.4. Counting triads

```{r, eval=FALSE}
df <- ts_triads(sims=sims3, simtype="twostep: weak coordination")  
```


### 3.3.5. Plot results of the triadcensus 

```{r, results='hold', fig.cap="Figure 3.3.5a. Triadcensus Model (Triads 030T & 120U)"}
dftest <- df[df$x=="030T" | df$x=="120U", ]
p1 <- ggplot(dftest, aes(x=x, y=y, fill=factor(type, levels=c("twostep: weak coordination"))))+ 
  geom_violin(position=position_dodge(.9)) + 
  stat_summary(fun = mean,
               geom = "errorbar",
               fun.max = function(x) mean(x) + sd(x),
               fun.min = function(x) mean(x) - sd(x),
               width=.1,
               color="red", position=position_dodge(.9)) + 
  stat_summary(fun = mean,
               geom = "point",
               color="red", position=position_dodge(.9)) +
  labs(x = "triad type", y = "triad count", fill="simulation type")
p1
```

<br> 
<br> 

```{r, results='hold', fig.cap="Figure 3.3.5b. Triadcensus Model 3 (Triads 120D & 120C)"}
dftest <- df[df$x=="120D" | df$x=="120C" , ]
p2 <- ggplot(dftest, aes(x=x, y=y, fill=factor(type, levels=c("twostep: simultaneity")))) + 
  geom_violin(position=position_dodge(.9)) + 
  stat_summary(fun = mean,
               geom = "errorbar",
               fun.max = function(x) mean(x) + sd(x),
               fun.min = function(x) mean(x) - sd(x),
               width=.1,
               color="red", position=position_dodge(.9)) + 
  stat_summary(fun = mean,
               geom = "point",
               color="red", position=position_dodge(.9)) +
  labs(x = "triad type", y = "triad count", fill="simulation type")
p2
```

<br> 
<br> 

```{r, results='hold', fig.cap="Figure 3.2.5c. Triadcensus Model 3 (Triads 210 & 300)"}
dftest <- df[df$x=="210" | df$x=="300" , ]
p3 <- ggplot(dftest, aes(x=x, y=y, fill=factor(type, levels=c("twostep: simultaneity")))) + 
  geom_violin(position=position_dodge(.9)) + 
  stat_summary(fun = mean,
               geom = "errorbar",
               fun.max = function(x) mean(x) + sd(x),
               fun.min = function(x) mean(x) - sd(x),
               width=.1,
               color="red", position=position_dodge(.9)) + 
  stat_summary(fun = mean,
               geom = "point",
               color="red", position=position_dodge(.9)) +
  labs(x = "triad type", y = "triad count", fill="simulation type")

p3

```




--- 

# 4. Conclusion  


---  
